# Generated by Django 4.2.16 on 2024-09-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_booking", models.CharField(max_length=50)),
                ("is_booked", models.BooleanField(default=False)),
            ],
        ),
    ]
