# Generated by Django 4.2.16 on 2024-09-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="name_booking",
            new_name="name_car_booking",
        ),
    ]
