# Generated by Django 4.2.16 on 2024-09-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_rename_name_booking_booking_name_car_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="image_car",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
